//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_prc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        public decimal codigo { get; set; }
        public Nullable<decimal> codigo_cliente { get; set; }
        public Nullable<decimal> codigo_producto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> pago_total { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
